/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package poc.logback

import org.slf4j.LoggerFactory

/**
 * Een app.
 *
 * Dit doet dus niet veel.
 *
 * @author Niels Frerichs
 */
class App {
    val logger = LoggerFactory.getLogger(App::class.java)
    val greeting: String
        get() {
            logger.info("In the greeting property")
            return "Hello world."
        }

    fun doSomeStuff(){
        val sysProp = System.getProperty("user.dir")
        logger.trace(sysProp)

        try{
            val property = System.getProperty("bestaat niet")
            if(property.isNullOrEmpty())
                throw Exception("Noel spoort niet")
        }
        catch(ex: java.lang.Exception){
            logger.error("wist dat dit zou gebeuren", ex)
        }
    }
}

fun main(args: Array<String>) {
    val app = App()
    println(app.greeting)
    app.doSomeStuff()
}
