/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package poc.hibernate

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    try {
        val jdbcer = Jdbcer()
        jdbcer.simpleQuery()
    }
    catch(ex : Exception){
        println(ex.message)
    }
}
