/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package poc.json

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    System.getenv().forEach { t, u ->
        println("$t=$u")
    }
    println(App().greeting)
}
