/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.poc.applicationcontext;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ApplicationContext ctx = new ClassPathXmlApplicationContext("hierstaatie");
        Object eenbeanindextx = ctx.getBean("eenbeanindextx");

        System.out.println(new App().getGreeting());
    }
}
