/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.poc.applicationcontext;

import org.poc.applicationcontext.func.SuperService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfig.class);
        SuperService bean = ctx.getBean(SuperService.class);

        System.out.println(bean.doSomethingAwesome());
    }
}
